name: BunkSystem
version: '${project.version}'
main: org.example.bunk.BunkSystem
api-version: '1.20'
commands:
  bank:
    description: Открыть меню банка или показать топ
    usage: /bank [top|reload]
  setcurrency:
    description: Установить валюту для банка
    usage: /setcurrency <diamond|emerald|gold|diamond_ore>
    permission: bankplugin.admin
  setbankname:
    description: Установить название банка
    usage: /setbankname <новое название>
    permission: bankplugin.admin
  balance:
    description: Проверить баланс
    usage: /balance
  transfer:
    description: Перевести средства другому игроку
    usage: /transfer <игрок> <количество>
  bhelp:
    description: Вывести справку по командам банка
    usage: /bhelp
permissions:
  bankplugin.admin:
    description: Доступ к админ-командам банка
    default: op
